add a bunch more error messages to signing
previously it was very hard to understand what went wrong because the
error just bubbled up to main.

before:
```
File exists (os error 17)
```

after:
```
Error: failed to save stable archive

Caused by:
    0: failed to create "build/host/signature-diffs"
    1: File exists (os error 17)
```