Give a helpful error if `x t certified-symbols.csv` has the wrong cfgs set
Previously this would error out later when comparing the CSV:
```
Generated report at /Users/jyn/work/ferrocene2/build/aarch64-apple-darwin/stage1-std/x86_64-unknown-ferrocene.certified/release/symbol-report.json
Diff of ferrocene/doc/symbol-report.csv and /Users/jyn/work/ferrocene2/build/aarch64-apple-darwin/stage1-std/x86_64-unknown-ferrocene.certified/release/symbol-report.json:
...
```

Now it gives a nicer error:
```
thread 'main' (39277673) panicked at src/bootstrap/src/ferrocene/test/certified_core_symbols.rs:32:13:
x t ferrocene/doc/symbol-report.csv requires `rust.debug-assertions-std=true`
```

Additionally, don't run this by default when `debug-assertions-std` is
disableed. I manually verified that `split-tasks.py test:docs` tests
this explicitly, which will run the test even if it will fail.