revert to uv version set in docker images
helps avoid

  cargo:warning=Compiler family detection failed due to error: ToolNotFound: failed to find tool "riscv64-unknown-linux-gnu-gcc": No such file or directory (os error 2)
  cargo:warning=Compiler family detection failed due to error: ToolNotFound: failed to find tool "riscv64-unknown-linux-gnu-g++": No such file or directory (os error 2)
  cargo:warning=Compiler family detection failed due to error: ToolNotFound: failed to find tool "riscv64-unknown-linux-gnu-g++": No such file or directory (os error 2)

  thread 'main' (1495) panicked at src/bootstrap/src/core/sanity.rs:87:13:

  couldn't find required command: "riscv64-unknown-linux-gnu-gcc"