bump dep, colored, for miri
Avoids this error

  Building stage1 compiler artifacts (stage0 -> stage1, aarch64-apple-darwin)
  error: failed to select a version for `colored`.
      ... required by package `ui_test v0.30.7`
      ... which satisfies dependency `ui_test = "^0.30.7"` (locked to 0.30.7) of package `clippy v0.1.98 (/Users/tshepang/ferrocene/pull/src/tools/clippy)`
  versions that meet the requirements `^3.1` are: 3.1.1

  all possible versions conflict with previously selected packages

    previously selected package `colored v3.0.0`
      ... which satisfies dependency `colored = "^3"` (locked to 3.0.0) of package `miri v0.1.0 (/Users/tshepang/ferrocene/pull/src/tools/miri)`