remove a stray attribute from a sloppy merge conflict resolution
  error: cannot use `const` closures outside of const contexts
     --> library/core/src/iter/traits/iterator.rs:236:13
      |
  236 |             const |accum, _elem| accum + 1,
      |             ^^^^^^^^^^^^^^^^^^^^