Disable builds for `x86_64-fuchsia`
CI fails because there is no std lib:
error: toolchain 'nightly-x86_64-unknown-linux-gnu' does not contain component 'rust-std' for target 'x86_64-fuchsia'