bump r-efi and r-efi-alloc deps
Matches upstream lockfile versions, and avoids this error:

  Creating a sysroot for stage1 compiler (use `rustup toolchain link 'name' build/host/stage1`)
  Building stage1 library artifacts (stage1 -> stage1, aarch64-apple-darwin)
  error: failed to select a version for `compiler_builtins`.
      ... required by package `r-efi-alloc v2.0.0`
      ... which satisfies dependency `r-efi-alloc = "^2.0.0"` (locked to 2.0.0) of package `std v0.0.0 (/Users/tshepang/ferrocene/pull/library/std)`
      ... which satisfies path dependency `std` (locked to 0.0.0) of package `sysroot v0.0.0 (/Users/tshepang/ferrocene/pull/library/sysroot)`
  versions that meet the requirements `^0.1.79` are: 0.1.160, 0.1.159, 0.1.158, 0.1.157, 0.1.156, 0.1.155, 0.1.154, 0.1.153, 0.1.152, 0.1.151, 0.1.150, 0.1.149, 0.1.148, 0.1.147, 0.1.146, 0.1.145, 0.1.144, 0.1.143, 0.1.142, 0.1.141, 0.1.140, 0.1.139, 0.1.138, 0.1.137, 0.1.136, 0.1.135, 0.1.134, 0.1.133, 0.1.132, 0.1.131, 0.1.130, 0.1.129, 0.1.128, 0.1.127, 0.1.126, 0.1.125, 0.1.124, 0.1.123, 0.1.122, 0.1.121, 0.1.120, 0.1.119, 0.1.118, 0.1.117, 0.1.116, 0.1.115, 0.1.114, 0.1.113, 0.1.112, 0.1.111, 0.1.110, 0.1.109, 0.1.108, 0.1.107, 0.1.106, 0.1.105, 0.1.104, 0.1.103, 0.1.102, 0.1.101, 0.1.100, 0.1.99, 0.1.98, 0.1.97, 0.1.96, 0.1.95, 0.1.94, 0.1.93, 0.1.92, 0.1.91, 0.1.90, 0.1.89, 0.1.88, 0.1.87, 0.1.86, 0.1.85, 0.1.84, 0.1.83, 0.1.82, 0.1.81, 0.1.80, 0.1.79

  package `compiler_builtins` links to the native library `compiler-rt`, but it conflicts with a previous package which links to `compiler-rt` as well:
  package `compiler_builtins v0.1.160 (/Users/tshepang/ferrocene/pull/library/compiler-builtins/compiler-builtins)`
      ... which satisfies path dependency `compiler_builtins` (locked to 0.1.160) of package `alloc v0.0.0 (/Users/tshepang/ferrocene/pull/library/alloc)`
      ... which satisfies path dependency `alloc` (locked to 0.0.0) of package `std v0.0.0 (/Users/tshepang/ferrocene/pull/library/std)`
      ... which satisfies path dependency `std` (locked to 0.0.0) of package `sysroot v0.0.0 (/Users/tshepang/ferrocene/pull/library/sysroot)`
  Only one package in the dependency graph may specify the same links value. This helps ensure that only one copy of a native library is linked in the final binary. Try to adjust your dependencies so that only one package uses the `links = "compiler-rt"` value. For more information, see https://doc.rust-lang.org/cargo/reference/resolver.html#links.

failed to select a version for `compiler_builtins` which could resolve this conflict