ci: Fix the binary size workflow
From the bootstrap error:

     thread 'main' panicked at src/bootstrap/src/core/config/config.rs:3283:21:
    `llvm.download-ci-llvm` cannot be set to `true` on CI. Use `if-unchanged` instead.

So do that. Additionally pin rustc to hopefully prevent similar
regressions in the future.

Some settings to increase log output were also applied.