Don't generate signatures on a public ledger for dev signings
Feels bad to touch the network and leave permanent records if we don't
have to.

I verified that `x test document-signatures` still works if and only if
`allow_dev_signing` is disabled. Otherwise cosign will complain that
it's missing the proper role:
```
Signature correct: /Users/jyn/work/ferrocene3/build/aarch64-apple-darwin/doc/qualification/internal-procedures
Error: missing signature file for role safety-manager
```