Blanket creates parent directories of the HTML report
Avoids the following error seen by Johann:
```
Error: failed to write HTML report to disk

Caused by:
    No such file or directory (os error 2)
```

Additionally, improves that error:
```
Error: failed to write HTML report to
/Users/jyn/src/ferrocene2/build/aarch64-unknown-ferrocene.certified/doc/certified-coverage-report.html
```